# Generated by Django 5.1.4 on 2024-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='car_type',
            field=models.CharField(blank=True, choices=[('passenger', 'Легковой'), ('cargo', 'Грузовой'), ('other', 'Другое')], max_length=10, verbose_name='Тип автомобиля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
    ]
