# Generated by Django 5.1.5 on 2025-02-03 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Город')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('car_type', models.CharField(blank=True, choices=[('passenger', 'Легковой'), ('cargo', 'Грузовой'), ('other', 'Другое')], max_length=10, verbose_name='Тип автомобиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
    ]
