# Generated by Django 5.2 on 2025-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_address_remove_customuser_car_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Почтовый индекс'),
        ),
    ]
