# Generated by Django 5.1.6 on 2025-03-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_historicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='show_in_catalog',
            field=models.BooleanField(default=True, verbose_name='Показывать в каталоге'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_catalog',
            field=models.BooleanField(default=True, verbose_name='Показывать в каталоге'),
        ),
    ]
