# Generated by Django 5.1.6 on 2025-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_historicalproduct_show_in_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_been_cancelled',
            field=models.BooleanField(default=False, verbose_name='Уже был отменён'),
        ),
    ]
