# Generated by Django 5.1.6 on 2025-03-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_has_been_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveIntegerField(default=0, verbose_name='id Товара'),
        ),
    ]
