# Generated by Django 5.1.7 on 2025-03-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='has_been_cancelled',
        ),
    ]
